# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://github.com/shuine
date_format: "ordinal"
title: 大树
subtitle: "大树的日志"
description: "大树个人博客"
keywords: 大树, shuine, shine,
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: yeshuxin
organization: XiaoMi, Inc.
organization_url: http://xiaomi.com
location: Beijing, China
email: yeshuxinxin@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: shuine/shuine.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: shuine
douban_username: shuine
facebook_username: shuine
weibo_username: shuine
zhihu_username: shuine
twitter_username: shuine

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: duoshuo
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: shuine
disqus_username: shuine
# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [php, mysql, Python, redis, mc, web]
skill_mobile_app_keywords: [Android, ios]
